rails6-bookers2-debug-ruby3-main/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "home/about" => "homes#about"
  get "/search", to: "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorite, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    	get "followings" => "relationships#followings", as: "followings"
    	get "followers" => "relationships#followers", as: "followers"
  end

  resources :notifications
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
  end
  resources :chats, only: [:show, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails6-bookers2-debug-ruby3-main/app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

rails6-bookers2-debug-ruby3-main/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = book.id
    @comment.save
  end

  def destroy
    @comment = BookComment.find(params[:id])
    @comment.destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

rails6-bookers2-debug-ruby3-main/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

rails6-bookers2-debug-ruby3-main/app/views/book_comments/_counter.html.erb
<i class="fa-regular fa-comment-dots"></i><%= @book.book_comments.count %>

rails6-bookers2-debug-ruby3-main/app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], url: book_book_comments_path(book), local:false do |f| %>
  <%= f.text_area :comment, rows: '5', class: "form-control", class: "w-100 comment-textarea" %>
  <%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

rails6-bookers2-debug-ruby3-main/app/views/book_comments/_index.html.erb
        <table>
          <tbody>
          <% book.book_comments.each do |book_comment| %>
        　　<tr>
        　　<td>
        　　    <%= link_to user_path(@user) do %>
                <%= image_tag book_comment.user.get_profile_image(50,50) %><br>
                <%= book_comment.user.name %>
              <% end %>
            </td>
            <td><%= book_comment.comment %></td>
            <td>
              <%= link_to "Destroy", book_book_comment_path(book, book_comment), class: "btn btn-sm btn-danger", method: :delete, remote: true %>
  
            </td>
          </tr>
          <% end %>
          </tbody>
        </table>

rails6-bookers2-debug-ruby3-main/app/views/book_comments/create.js.erb
$('.comment-textarea').val("");
$('.book-comment-counter').html("<%= j(render 'book_comments/counter', book: @comment.book) %>");
$('.book-comment-index').html("<%= j(render 'book_comments/index', book: @comment.book) %>");

rails6-bookers2-debug-ruby3-main/app/views/book_comments/destroy.js.erb
$('.book-comment-counter').html("<%= j(render 'book_comments/counter', book: @comment.book) %>");
$('.comment-index').html("<%= j(render 'book_comments/index', book: @comment.book) %>");